# Generated by Django 3.2.10 on 2022-01-11 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InboundMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('from_email', models.EmailField(max_length=254)),
                ('to_email', models.CharField(blank=True, max_length=255)),
                ('cc_email', models.CharField(blank=True, max_length=255)),
                ('bcc_email', models.CharField(blank=True, max_length=255)),
                ('original_recipient', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('reply_to', models.CharField(blank=True, max_length=255)),
                ('mailbox_hash', models.CharField(blank=True, max_length=255)),
                ('date', models.DateTimeField()),
                ('text_body', models.TextField(blank=True)),
                ('html_body', models.TextField(blank=True)),
                ('stripped_text_reply', models.TextField(blank=True)),
                ('tag', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InboundMailHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.TextField(blank=True)),
                ('parent_mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='postmark_inbound.inboundmail')),
            ],
        ),
        migrations.CreateModel(
            name='InboundMailDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('FROM', 'FROM'), ('TO', 'TO'), ('CC', 'CC'), ('BCC', 'BCC')], max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('mailbox_hash', models.CharField(blank=True, max_length=255)),
                ('parent_mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_details', to='postmark_inbound.inboundmail')),
            ],
        ),
        migrations.CreateModel(
            name='InboundMailAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
                ('content', models.FileField(upload_to='attachments')),
                ('content_id', models.CharField(blank=True, max_length=255)),
                ('content_length', models.IntegerField()),
                ('parent_mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='postmark_inbound.inboundmail')),
            ],
        ),
    ]
